/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

export function Slider(props) {
  const { nodes, materials } = useGLTF("/fidget_slider.glb");
  const roughnessMap = useTexture("./fidget_roughness_map.png");

  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube012.geometry} position={[0, 1.096, 0.669]}>
        <meshStandardMaterial color='#CF0B0E' roughness={0.5} roughnessMap={roughnessMap} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/fidget_slider.glb");
